In [8]:
import tensorflow as tf
#tf.enable_eager_execution()		# 즉시 실행하도록

# Data
x_data = [1, 2, 3, 4, 5]
y_data = [1, 2, 3, 4, 5]

# W, b initialize
W = tf.Variable(2.9)
b = tf.Variable(0.5)

learning_rate = 0.01

for i in range(100):	# W, b update
    # Gradient descent
    with tf.GradientTape() as tape:	
        hypothesis = W * x_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    W_grad, b_grad = tape.gradient(cost, [W, b])
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    if i%10==0:
        print('{:5}|{:10.4}|{:10.4}|{:10.6f}'.format(i, W.numpy(), b.numpy(), cost))

    0|     2.452|     0.376| 45.660004
   10|     1.104|  0.003398|  0.206336
   20|     1.013|  -0.02091|  0.001026
   30|     1.007|  -0.02184|  0.000093
   40|     1.006|  -0.02123|  0.000083
   50|     1.006|  -0.02053|  0.000077
   60|     1.005|  -0.01984|  0.000072
   70|     1.005|  -0.01918|  0.000067
   80|     1.005|  -0.01854|  0.000063
   90|     1.005|  -0.01793|  0.000059


In [9]:
print(W * 5 + b)	# 5.0066934
print(W * 2.5 + b)	# 2.4946523

tf.Tensor(5.0066934, shape=(), dtype=float32)
tf.Tensor(2.4946523, shape=(), dtype=float32)


In [11]:
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([1, 2, 3])

def cost_func(W, X, Y):
    c = 0
    for i in range(len(X)):
        c += (W * X[i] - Y[i]) ** 2
    return c / len(X)

for feed_W in np.linspace(-3, 5, num=15):
    curr_cost = cost_func(feed_W, X, Y)
    print("{:6.3f} | {:10.5f}".format(feed_W, curr_cost))

-3.000 |   74.66667
-2.429 |   54.85714
-1.857 |   38.09524
-1.286 |   24.38095
-0.714 |   13.71429
-0.143 |    6.09524
 0.429 |    1.52381
 1.000 |    0.00000
 1.571 |    1.52381
 2.143 |    6.09524
 2.714 |   13.71429
 3.286 |   24.38095
 3.857 |   38.09524
 4.429 |   54.85714
 5.000 |   74.66667


In [12]:

X = np.array([1, 2, 3])
Y = np.array([1, 2, 3])

def cost_func(W, X, Y):
  hypothesis = X * W
  return tf.reduce_mean(tf.square(hypothesis - Y))

W_values = np.linspace(-3, 5, num=15)
cost_values = []

for feed_W in W_values:
    curr_cost = cost_func(feed_W, X, Y)
    cost_values.append(curr_cost)
    print("{:6.3f} | {:10.5f}".format(feed_W, curr_cost))

-3.000 |   74.66667
-2.429 |   54.85714
-1.857 |   38.09524
-1.286 |   24.38095
-0.714 |   13.71429
-0.143 |    6.09524
 0.429 |    1.52381
 1.000 |    0.00000
 1.571 |    1.52381
 2.143 |    6.09524
 2.714 |   13.71429
 3.286 |   24.38095
 3.857 |   38.09524
 4.429 |   54.85714
 5.000 |   74.66667


In [18]:
tf.random.set_seed(0)  # for reproducibility 이 코드를 다시 수행했을 때도 동일하게 똑같이 진행이 될 수 있도록 하기 위해서 랜덤 시드를 특정한 값으로 초기화

x_data = [1., 2., 3., 4.]
y_data = [1., 3., 5., 7.]

W = tf.Variable(tf.random.normal([1], -100., 100.))

for step in range(300):
    hypothesis = W * x_data
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))

    alpha = 0.01
    gradient = tf.reduce_mean(tf.multiply(tf.multiply(W, x_data) - y_data, x_data))
    descent = W - tf.multiply(alpha, gradient)
    W.assign(descent)
    
    if step % 10 == 0:
        print('{:5} | {:10.4f} | {:10.6f}'.format(
            step, cost.numpy(), W.numpy()[0]))

    0 | 18332.2188 |  47.398293
   10 |  3855.3564 |  22.638384
   20 |   810.9046 |  11.283927
   30 |   170.6631 |   6.076973
   40 |    36.0217 |   3.689155
   50 |     7.7069 |   2.594144
   60 |     1.7524 |   2.091991
   70 |     0.5001 |   1.861713
   80 |     0.2368 |   1.756112
   90 |     0.1814 |   1.707684
  100 |     0.1698 |   1.685477
  110 |     0.1673 |   1.675292
  120 |     0.1668 |   1.670622
  130 |     0.1667 |   1.668481
  140 |     0.1667 |   1.667498
  150 |     0.1667 |   1.667048
  160 |     0.1667 |   1.666842
  170 |     0.1667 |   1.666747
  180 |     0.1667 |   1.666703
  190 |     0.1667 |   1.666684
  200 |     0.1667 |   1.666674
  210 |     0.1667 |   1.666670
  220 |     0.1667 |   1.666668
  230 |     0.1667 |   1.666667
  240 |     0.1667 |   1.666667
  250 |     0.1667 |   1.666667
  260 |     0.1667 |   1.666667
  270 |     0.1667 |   1.666667
  280 |     0.1667 |   1.666667
  290 |     0.1667 |   1.666667


In [19]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b  = tf.Variable(tf.random.normal([1]))

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |    7575.0693
   50 |     140.8121
  100 |      58.1745
  150 |      57.1111
  200 |      56.9531
  250 |      56.8058
  300 |      56.6587
  350 |      56.5122
  400 |      56.3662
  450 |      56.2205
  500 |      56.0753
  550 |      55.9304
  600 |      55.7858
  650 |      55.6417
  700 |      55.4979
  750 |      55.3544
  800 |      55.2114
  850 |      55.0688
  900 |      54.9265
  950 |      54.7847
 1000 |      54.6432


In [24]:
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]	# data 3열까지(입력)
y = data[:, [-1]]	# data 4열(출력)

W = tf.Variable(tf.random.normal([3, 1]))	# 3행 1열
b = tf.Variable(tf.random.normal([1]))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b	# matmul => matrix multiply(행렬곱)

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |  4567.1289
  100 |     2.3131
  200 |     1.7445
  300 |     1.7378
  400 |     1.7313
  500 |     1.7249
  600 |     1.7184
  700 |     1.7121
  800 |     1.7057
  900 |     1.6994
 1000 |     1.6931
 1100 |     1.6868
 1200 |     1.6805
 1300 |     1.6743
 1400 |     1.6681
 1500 |     1.6621
 1600 |     1.6560
 1700 |     1.6499
 1800 |     1.6438
 1900 |     1.6378
 2000 |     1.6319


In [2]:
import tensorflow as tf
x_train = [[1., 2.],
          [2., 3.],
          [3., 1.],
          [4., 3.],
          [5., 3.],
          [6., 2.]]
y_train = [[0.],
          [0.],
          [0.],
          [1.],
          [1.],
          [1.]]

x_test = [[5.,2.]]	#데이터셋 설정
y_test = [[1.]]

# Batch Size는 한 번에 학습시킬 Size로 정한다.
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(len(x_train))
W = tf.Variable(tf.zeros([2,1]), name='weight')
b = tf.Variable(tf.zeros([1]), name='bias')	# W, b 초기설정

def logistic_regression(features):	# Sigmoid 함수를 가설로 선언
    hypothesis  = tf.divide(1., 1. + tf.exp(tf.matmul(features, W) + b))
    return hypothesis

def loss_fn(hypothesis, features, labels):	# 가설을 검증할 Cost 함수 정의
    cost = -tf.reduce_mean(labels * tf.math.log(logistic_regression(features)) + (1 - labels) * tf.math.log(1 - hypothesis))
    return cost
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

def accuracy_fn(hypothesis, labels):	# 예측값이 0.5보다 크면 1 반환, 아니면 0 반환
    predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
    accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, labels), dtype=tf.int32))
    return accuracy

def grad(features, labels):	# 경사값 계산
    with tf.GradientTape() as tape:
        loss_value = loss_fn(logistic_regression(features),features,labels)
    return tape.gradient(loss_value, [W,b])

EPOCHS = 1001

for step in range(EPOCHS):
    for features, labels  in iter(dataset):
        grads = grad(features, labels)
        optimizer.apply_gradients(grads_and_vars=zip(grads,[W,b]))
        if step % 100 == 0:
            print("Iter: {}, Loss: {:.4f}".format(step, loss_fn(logistic_regression(features),features,labels)))
test_acc = accuracy_fn(logistic_regression(x_test),y_test)
print("Testset Accuracy: {:.4f}".format(test_acc))

Iter: 0, Loss: 0.6874
Iter: 100, Loss: 0.5776
Iter: 200, Loss: 0.5349
Iter: 300, Loss: 0.5054
Iter: 400, Loss: 0.4838
Iter: 500, Loss: 0.4671
Iter: 600, Loss: 0.4535
Iter: 700, Loss: 0.4420
Iter: 800, Loss: 0.4319
Iter: 900, Loss: 0.4228
Iter: 1000, Loss: 0.4144
Testset Accuracy: 1.0000


In [10]:
import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

#convert into numpy and float format
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3	# num classes (A, B, C - ONE-HOT-ENCODING)

In [11]:
#Weight and bias setting
W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')
variables = [W, b]

print(W,b)


# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.6701146 , -1.5312574 ,  0.73224336],
       [-0.37725016, -0.62765795, -2.5822446 ],
       [-0.67284334,  0.25653654, -0.3872052 ],
       [-0.040566  , -1.2135769 , -0.74410707]], dtype=float32)> <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 0.83098805,  1.1333642 , -2.021677  ], dtype=float32)>
tf.Tensor(
[[7.8521639e-01 2.1330991e-01 1.4736763e-03]
 [7.3885781e-01 2.1635184e-01 4.4790406e-02]
 [9.3267387e-01 1.1052889e-02 5.6273289e-02]
 [8.1645322e-01 8.1190309e-03 1.7542771e-01]
 [9.7152317e-01 2.8476795e-02 5.5822547e-09]
 [9.6908945e-01 3.0741360e-02 1.6914570e-04]
 [9.7133505e-01 2.8664880e-02 3.3331048e-08]
 [9.8231226e-01 1.7687758e-02 2.4469222e-09]], shape=(8, 3), dtype=float32)


In [12]:
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[1.9345909e-01 3.7530765e-06 8.0653715e-01]], shape=(1, 3), dtype=float32)


In [14]:
def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(3.0505724, shape=(), dtype=float32)


In [15]:
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        cost = cost_fn(X, Y)
        grads = tape.gradient(cost, variables)
        return grads
    
print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.2776283 , -0.6478476 , -0.6297807 ],
       [ 1.5626819 , -1.097654  , -0.46502787],
       [ 2.4111671 , -1.6839983 , -0.72716886],
       [ 2.5565305 , -1.8308179 , -0.7257124 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.6459326 , -0.30569944, -0.34023324], dtype=float32)>]


In [30]:
def fit(X, Y, epochs=2000, verbose=100):
    optimizer = tf.optimizers.SGD(learning_rate=0.1, name='SGD')
    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1: 2.366735
Loss at epoch 100: 0.828323
Loss at epoch 200: 0.713423
Loss at epoch 300: 0.645316
Loss at epoch 400: 0.590446
Loss at epoch 500: 0.540575
Loss at epoch 600: 0.493011
Loss at epoch 700: 0.446594
Loss at epoch 800: 0.400709
Loss at epoch 900: 0.355054
Loss at epoch 1000: 0.309804
Loss at epoch 1100: 0.267477
Loss at epoch 1200: 0.242524
Loss at epoch 1300: 0.230401
Loss at epoch 1400: 0.219474
Loss at epoch 1500: 0.209489
Loss at epoch 1600: 0.200331
Loss at epoch 1700: 0.191903
Loss at epoch 1800: 0.184123
Loss at epoch 1900: 0.176922
Loss at epoch 2000: 0.170238


In [31]:
# prediction
a = hypothesis(x_data)
print(a)
print(tf.argmax(a, 1))
print(tf.argmax(y_data, 1)) # matches with y_data

tf.Tensor(
[[2.5506436e-06 8.7754463e-04 9.9911994e-01]
 [1.0952300e-03 9.1185570e-02 9.0771919e-01]
 [1.1513348e-07 1.7789358e-01 8.2210630e-01]
 [1.5890674e-06 8.3665663e-01 1.6334181e-01]
 [2.7380353e-01 7.1308005e-01 1.3116424e-02]
 [1.4408457e-01 8.5591483e-01 5.6868009e-07]
 [7.3764908e-01 2.6234201e-01 8.8387587e-06]
 [9.1215891e-01 8.7841049e-02 1.2655407e-07]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


In [54]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.int32) #tf1.13.1에서는 np.int32, 이전에는 np.float32
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

nb_classes = 7  # 0 ~ 6

# Make Y data as onehot shape
Y_one_hot = tf.one_hot(list(y_data), nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

print(x_data.shape, Y_one_hot.shape)

(101, 16) (101, 7)


In [59]:
#Weight and bias setting
W = tf.Variable(tf.random.normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')
variables = [W, b]

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def logit_fn(X):
    return tf.matmul(tf.dtypes.cast(X,tf.float32), W) + b

def hypothesis(X):
    return tf.nn.softmax(logit_fn(X))

def cost_fn(X, Y):
    logits = logit_fn(X)
    cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits,
                                                           labels=Y)
    cost = tf.reduce_mean(cost_i)
    
    return cost

def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)
        return grads
    
def prediction(X, Y):
    pred = tf.argmax(hypothesis(X), 1)
    correct_prediction = tf.equal(pred, tf.argmax(Y, 1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

    return accuracy

In [61]:
def fit(X, Y, epochs=1000, verbose=100):
    optimizer =  tf.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            # print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            acc = prediction(X, Y).numpy()
            loss = cost_fn(X, Y).numpy() 
            print('Steps: {} Loss: {}, Acc: {}'.format(i+1, loss, acc))

fit(x_data, Y_one_hot)

Steps: 1 Loss: 0.09754873067140579, Acc: 0.9900990128517151
Steps: 100 Loss: 0.08912097662687302, Acc: 0.9900990128517151
Steps: 200 Loss: 0.08197152614593506, Acc: 1.0
Steps: 300 Loss: 0.07589178532361984, Acc: 1.0
Steps: 400 Loss: 0.07066173851490021, Acc: 1.0
Steps: 500 Loss: 0.06611780822277069, Acc: 1.0
Steps: 600 Loss: 0.06213541328907013, Acc: 1.0
Steps: 700 Loss: 0.05861821398139, Acc: 1.0
Steps: 800 Loss: 0.055490314960479736, Acc: 1.0
Steps: 900 Loss: 0.052691176533699036, Acc: 1.0
Steps: 1000 Loss: 0.05017192289233208, Acc: 1.0
